import { TranslateService } from "@ngx-translate/core";
import { BaseModel } from "./base.model";
import { Eventgrp, MyEventgrp } from "./eventgrp.model";
export interface HolidayList {
    employeeid?: string;
    dateId?: string;
    dateid?: string;
    time0id?: string;
    sequence?: string;
    c_tm_bg?: number;
    c_tm_en?: number;
    m_tm_bg?: number;
    m_tm_en?: number;
    c_dt_bg?: string;
    c_dt_en?: string;
    m_dt_bg?: string;
    m_dt_en?: string;
    lt?: number;
    c_lv?: number;
    m_lv?: number;
    tr_type?: string;
    ac_ot?: number;
    ap_ot?: number;
    iswork?: number;
    dt_in_inzone?: string;
    dt_out_inzone?: string;
    tm_in_inzone?: number;
    tm_out_inzone?: number;
    dt_in_outzone?: string;
    dt_out_outzone?: string;
    tm_in_outzone?: number;
    tm_out_outzone?: number;
    ot1?: number;
    ot5?: number;
    ot2?: number;
    ot3?: number;
    eventgrp?: Eventgrp;
    unused1?: number;
    unused2?: number;
    unused3?: number;
    unused4?: number;
    unused5?: number;
    unused6?: number;
    unused7?: number;
    unused8?: number;
    unused9?: number;
    unused10?: number;
    salatype?: string;
    currency?: string;
    exchange?: number;
    salary?: string;
    hour_d?: number;
    every?: string;
    dt_breakin?: string;
    tm_breakin?: number;
    dt_breakout?: string;
    tm_breakout?: number;
    emp_level?: string;
    bossid?: string;
    daytype?: string;
    hour_s?: number;
    date_actual?: string;
    o_tm_bg?: number;
    o_tm_en?: number;
    o_dt_bg?: string;
    o_dt_en?: string;
    source_in?: string;
    source_out?: string;
    ot_before?: number;
    ot_after?: number;
    sh_tm_bg?: number;
    sh_tm_en?: number;
    sh_dt_bg?: string;
    sh_dt_en?: string;
    warn11?: string;
    warn12?: string;
    runno?: number;
    prused1?: number;
    prused2?: number;
    prused3?: number;
    prused4?: number;
    prused5?: number;
    pl?: string;
    bk_ot_dt_in?: string;
    bk_ot_dt_out?: string;
    bk_ot_tm_in?: number;
    bk_ot_tm_out?: number;
}

export class MyHolidayList extends BaseModel implements HolidayList {
    employeeid: string | undefined;
    dateId?: string | undefined;
    dateid?: string | undefined;
    time0id?: string | undefined;
    sequence?: string | undefined;
    c_tm_bg?: number | undefined;
    c_tm_en?: number | undefined;
    m_tm_bg?: number | undefined;
    m_tm_en?: number | undefined;
    c_dt_bg?: string | undefined;
    c_dt_en?: string | undefined;
    m_dt_bg?: string | undefined;
    m_dt_en?: string | undefined;
    lt?: number | undefined;
    c_lv?: number | undefined;
    m_lv?: number | undefined;
    tr_type?: string | undefined;
    ac_ot?: number | undefined;
    ap_ot?: number | undefined;
    iswork?: number | undefined;
    dt_in_inzone?: string | undefined;
    dt_out_inzone?: string | undefined;
    tm_in_inzone?: number | undefined;
    tm_out_inzone?: number | undefined;
    dt_in_outzone?: string | undefined;
    dt_out_outzone?: string | undefined;
    tm_in_outzone?: number | undefined;
    tm_out_outzone?: number | undefined;
    ot1?: number | undefined;
    ot5?: number | undefined;
    ot2?: number | undefined;
    ot3?: number | undefined;
    eventgrp?: Eventgrp | undefined;
    unused1?: number | undefined;
    unused2?: number | undefined;
    unused3?: number | undefined;
    unused4?: number | undefined;
    unused5?: number | undefined;
    unused6?: number | undefined;
    unused7?: number | undefined;
    unused8?: number | undefined;
    unused9?: number | undefined;
    unused10?: number | undefined;
    salatype?: string | undefined;
    currency?: string | undefined;
    exchange?: number | undefined;
    salary?: string | undefined;
    hour_d?: number | undefined;
    every?: string | undefined;
    dt_breakin?: string | undefined;
    tm_breakin?: number | undefined;
    dt_breakout?: string | undefined;
    tm_breakout?: number | undefined;
    emp_level?: string | undefined;
    bossid?: string | undefined;
    daytype?: string | undefined;
    hour_s?: number | undefined;
    date_actual?: string | undefined;
    o_tm_bg?: number | undefined;
    o_tm_en?: number | undefined;
    o_dt_bg?: string | undefined;
    o_dt_en?: string | undefined;
    source_in?: string | undefined;
    source_out?: string | undefined;
    ot_before?: number | undefined;
    ot_after?: number | undefined;
    sh_tm_bg?: number | undefined;
    sh_tm_en?: number | undefined;
    sh_dt_bg?: string | undefined;
    sh_dt_en?: string | undefined;
    warn11?: string | undefined;
    warn12?: string | undefined;
    runno?: number | undefined;
    prused1?: number | undefined;
    prused2?: number | undefined;
    prused3?: number | undefined;
    prused4?: number | undefined;
    prused5?: number | undefined;
    pl?: string | undefined;
    bk_ot_dt_in?: string | undefined;
    bk_ot_dt_out?: string | undefined;
    bk_ot_tm_in?: number | undefined;
    bk_ot_tm_out?: number | undefined;
    constructor(data: Partial<HolidayList>, tranSer: TranslateService) {
        super(data, tranSer);
        this.eventgrp = data.eventgrp ? new MyEventgrp(data.eventgrp!, this.translateService) : data.eventgrp
    }

}
