import { BaseModel, TranslateService } from './base.model';
import { ShiftListModel, MyShiftListModel } from './shift-list.model';

/**
 * Shift time list model
 */
export interface ShiftTimeListModel {
  yearId?: number;
  monthId?: number;
  time0Id?: string;
  time011?: ShiftListModel;
  time012?: ShiftListModel;
  time013?: ShiftListModel;
  time021?: ShiftListModel;
  time022?: ShiftListModel;
  time023?: ShiftListModel;
  time031?: ShiftListModel;
  time032?: ShiftListModel;
  time033?: ShiftListModel;
  time041?: ShiftListModel;
  time042?: ShiftListModel;
  time043?: ShiftListModel;
  time051?: ShiftListModel;
  time052?: ShiftListModel;
  time053?: ShiftListModel;
  time061?: ShiftListModel;
  time062?: ShiftListModel;
  time063?: ShiftListModel;
  time071?: ShiftListModel;
  time072?: ShiftListModel;
  time073?: ShiftListModel;
  time081?: ShiftListModel;
  time082?: ShiftListModel;
  time083?: ShiftListModel;
  time091?: ShiftListModel;
  time092?: ShiftListModel;
  time093?: ShiftListModel;
  time101?: ShiftListModel;
  time102?: ShiftListModel;
  time103?: ShiftListModel;
  time111?: ShiftListModel;
  time112?: ShiftListModel;
  time113?: ShiftListModel;
  time121?: ShiftListModel;
  time122?: ShiftListModel;
  time123?: ShiftListModel;
  time131?: ShiftListModel;
  time132?: ShiftListModel;
  time133?: ShiftListModel;
  time141?: ShiftListModel;
  time142?: ShiftListModel;
  time143?: ShiftListModel;
  time151?: ShiftListModel;
  time152?: ShiftListModel;
  time153?: ShiftListModel;
  time161?: ShiftListModel;
  time162?: ShiftListModel;
  time163?: ShiftListModel;
  time171?: ShiftListModel;
  time172?: ShiftListModel;
  time173?: ShiftListModel;
  time181?: ShiftListModel;
  time182?: ShiftListModel;
  time183?: ShiftListModel;
  time191?: ShiftListModel;
  time192?: ShiftListModel;
  time193?: ShiftListModel;
  time201?: ShiftListModel;
  time202?: ShiftListModel;
  time203?: ShiftListModel;
  time211?: ShiftListModel;
  time212?: ShiftListModel;
  time213?: ShiftListModel;
  time221?: ShiftListModel;
  time222?: ShiftListModel;
  time223?: ShiftListModel;
  time231?: ShiftListModel;
  time232?: ShiftListModel;
  time233?: ShiftListModel;
  time241?: ShiftListModel;
  time242?: ShiftListModel;
  time243?: ShiftListModel;
  time251?: ShiftListModel;
  time252?: ShiftListModel;
  time253?: ShiftListModel;
  time261?: ShiftListModel;
  time262?: ShiftListModel;
  time263?: ShiftListModel;
  time271?: ShiftListModel;
  time272?: ShiftListModel;
  time273?: ShiftListModel;
  time281?: ShiftListModel;
  time282?: ShiftListModel;
  time283?: ShiftListModel;
  time291?: ShiftListModel;
  time292?: ShiftListModel;
  time293?: ShiftListModel;
  time301?: ShiftListModel;
  time302?: ShiftListModel;
  time303?: ShiftListModel;
  time311?: ShiftListModel;
  time312?: ShiftListModel;
  time313?: ShiftListModel;
}

export class MyShifTimetListModel extends BaseModel implements ShiftTimeListModel {
  yearId: number | undefined;
  monthId: number | undefined;
  time0Id: string | undefined;
  time011: ShiftListModel | undefined;
  time012: ShiftListModel | undefined;
  time013: ShiftListModel | undefined;
  time021: ShiftListModel | undefined;
  time022: ShiftListModel | undefined;
  time023: ShiftListModel | undefined;
  time031: ShiftListModel | undefined;
  time032: ShiftListModel | undefined;
  time033: ShiftListModel | undefined;
  time041: ShiftListModel | undefined;
  time042: ShiftListModel | undefined;
  time043: ShiftListModel | undefined;
  time051: ShiftListModel | undefined;
  time052: ShiftListModel | undefined;
  time053: ShiftListModel | undefined;
  time061: ShiftListModel | undefined;
  time062: ShiftListModel | undefined;
  time063: ShiftListModel | undefined;
  time071: ShiftListModel | undefined;
  time072: ShiftListModel | undefined;
  time073: ShiftListModel | undefined;
  time081: ShiftListModel | undefined;
  time082: ShiftListModel | undefined;
  time083: ShiftListModel | undefined;
  time091: ShiftListModel | undefined;
  time092: ShiftListModel | undefined;
  time093: ShiftListModel | undefined;
  time101: ShiftListModel | undefined;
  time102: ShiftListModel | undefined;
  time103: ShiftListModel | undefined;
  time111: ShiftListModel | undefined;
  time112: ShiftListModel | undefined;
  time113: ShiftListModel | undefined;
  time121: ShiftListModel | undefined;
  time122: ShiftListModel | undefined;
  time123: ShiftListModel | undefined;
  time131: ShiftListModel | undefined;
  time132: ShiftListModel | undefined;
  time133: ShiftListModel | undefined;
  time141: ShiftListModel | undefined;
  time142: ShiftListModel | undefined;
  time143: ShiftListModel | undefined;
  time151: ShiftListModel | undefined;
  time152: ShiftListModel | undefined;
  time153: ShiftListModel | undefined;
  time161: ShiftListModel | undefined;
  time162: ShiftListModel | undefined;
  time163: ShiftListModel | undefined;
  time171: ShiftListModel | undefined;
  time172: ShiftListModel | undefined;
  time173: ShiftListModel | undefined;
  time181: ShiftListModel | undefined;
  time182: ShiftListModel | undefined;
  time183: ShiftListModel | undefined;
  time191: ShiftListModel | undefined;
  time192: ShiftListModel | undefined;
  time193: ShiftListModel | undefined;
  time201: ShiftListModel | undefined;
  time202: ShiftListModel | undefined;
  time203: ShiftListModel | undefined;
  time211: ShiftListModel | undefined;
  time212: ShiftListModel | undefined;
  time213: ShiftListModel | undefined;
  time221: ShiftListModel | undefined;
  time222: ShiftListModel | undefined;
  time223: ShiftListModel | undefined;
  time231: ShiftListModel | undefined;
  time232: ShiftListModel | undefined;
  time233: ShiftListModel | undefined;
  time241: ShiftListModel | undefined;
  time242: ShiftListModel | undefined;
  time243: ShiftListModel | undefined;
  time251: ShiftListModel | undefined;
  time252: ShiftListModel | undefined;
  time253: ShiftListModel | undefined;
  time261: ShiftListModel | undefined;
  time262: ShiftListModel | undefined;
  time263: ShiftListModel | undefined;
  time271: ShiftListModel | undefined;
  time272: ShiftListModel | undefined;
  time273: ShiftListModel | undefined;
  time281: ShiftListModel | undefined;
  time282: ShiftListModel | undefined;
  time283: ShiftListModel | undefined;
  time291: ShiftListModel | undefined;
  time292: ShiftListModel | undefined;
  time293: ShiftListModel | undefined;
  time301: ShiftListModel | undefined;
  time302: ShiftListModel | undefined;
  time303: ShiftListModel | undefined;
  time311: ShiftListModel | undefined;
  time312: ShiftListModel | undefined;
  time313: ShiftListModel | undefined;

  constructor(data: Partial<ShiftTimeListModel>, translateService: TranslateService) {
    super(data, translateService);
    this.yearId = data.yearId;
    this.monthId = data.monthId;
    this.time0Id = data.time0Id;
    // Helper function to create ShiftListModel instances
    const createShiftList = (item: any) =>
      item ? new MyShiftListModel(item, translateService) : undefined;
    this.time011 = createShiftList(data.time011);
    this.time012 = createShiftList(data.time012);
    this.time013 = createShiftList(data.time013);
    this.time021 = createShiftList(data.time021);
    this.time022 = createShiftList(data.time022);
    this.time023 = createShiftList(data.time023);
    this.time031 = createShiftList(data.time031);
    this.time032 = createShiftList(data.time032);
    this.time033 = createShiftList(data.time033);
    this.time041 = createShiftList(data.time041);
    this.time042 = createShiftList(data.time042);
    this.time043 = createShiftList(data.time043);
    this.time051 = createShiftList(data.time051);
    this.time052 = createShiftList(data.time052);
    this.time053 = createShiftList(data.time053);
    this.time061 = createShiftList(data.time061);
    this.time062 = createShiftList(data.time062);
    this.time063 = createShiftList(data.time063);
    this.time071 = createShiftList(data.time071);
    this.time072 = createShiftList(data.time072);
    this.time073 = createShiftList(data.time073);
    this.time081 = createShiftList(data.time081);
    this.time082 = createShiftList(data.time082);
    this.time083 = createShiftList(data.time083);
    this.time091 = createShiftList(data.time091);
    this.time092 = createShiftList(data.time092);
    this.time093 = createShiftList(data.time093);
    this.time101 = createShiftList(data.time101);
    this.time102 = createShiftList(data.time102);
    this.time103 = createShiftList(data.time103);
    this.time111 = createShiftList(data.time111);
    this.time112 = createShiftList(data.time112);
    this.time113 = createShiftList(data.time113);
    this.time121 = createShiftList(data.time121);
    this.time122 = createShiftList(data.time122);
    this.time123 = createShiftList(data.time123);
    this.time131 = createShiftList(data.time131);
    this.time132 = createShiftList(data.time132);
    this.time133 = createShiftList(data.time133);
    this.time141 = createShiftList(data.time141);
    this.time142 = createShiftList(data.time142);
    this.time143 = createShiftList(data.time143);
    this.time151 = createShiftList(data.time151);
    this.time152 = createShiftList(data.time152);
    this.time153 = createShiftList(data.time153);
    this.time161 = createShiftList(data.time161);
    this.time162 = createShiftList(data.time162);
    this.time163 = createShiftList(data.time163);
    this.time171 = createShiftList(data.time171);
    this.time172 = createShiftList(data.time172);
    this.time173 = createShiftList(data.time173);
    this.time181 = createShiftList(data.time181);
    this.time182 = createShiftList(data.time182);
    this.time183 = createShiftList(data.time183);
    this.time191 = createShiftList(data.time191);
    this.time192 = createShiftList(data.time192);
    this.time193 = createShiftList(data.time193);
    this.time201 = createShiftList(data.time201);
    this.time202 = createShiftList(data.time202);
    this.time203 = createShiftList(data.time203);
    this.time211 = createShiftList(data.time211);
    this.time212 = createShiftList(data.time212);
    this.time213 = createShiftList(data.time213);
    this.time221 = createShiftList(data.time221);
    this.time222 = createShiftList(data.time222);
    this.time223 = createShiftList(data.time223);
    this.time231 = createShiftList(data.time231);
    this.time232 = createShiftList(data.time232);
    this.time233 = createShiftList(data.time233);
    this.time241 = createShiftList(data.time241);
    this.time242 = createShiftList(data.time242);
    this.time243 = createShiftList(data.time243);
    this.time251 = createShiftList(data.time251);
    this.time252 = createShiftList(data.time252);
    this.time253 = createShiftList(data.time253);
    this.time261 = createShiftList(data.time261);
    this.time262 = createShiftList(data.time262);
    this.time263 = createShiftList(data.time263);
    this.time271 = createShiftList(data.time271);
    this.time272 = createShiftList(data.time272);
    this.time273 = createShiftList(data.time273);
    this.time281 = createShiftList(data.time281);
    this.time282 = createShiftList(data.time282);
    this.time283 = createShiftList(data.time283);
    this.time291 = createShiftList(data.time291);
    this.time292 = createShiftList(data.time292);
    this.time293 = createShiftList(data.time293);
    this.time301 = createShiftList(data.time301);
    this.time302 = createShiftList(data.time302);
    this.time303 = createShiftList(data.time303);
    this.time311 = createShiftList(data.time311);
    this.time312 = createShiftList(data.time312);
    this.time313 = createShiftList(data.time313);
  }
}

