import { TranslateService } from "@ngx-translate/core";
import { BaseModel } from "./base.model";
import { MyShiftListModel, ShiftListModel } from "./shiftlist.model";

export interface ShiftTimeListModel {
  yearId?: number;
  monthId?: number;
  time0Id?: string;
  time011?: ShiftListModel;
  time012?: ShiftListModel;
  time013?: ShiftListModel;
  time021?: ShiftListModel;
  time022?: ShiftListModel;
  time023?: ShiftListModel;
  time031?: ShiftListModel;
  time032?: ShiftListModel;
  time033?: ShiftListModel;
  time041?: ShiftListModel;
  time042?: ShiftListModel;
  time043?: ShiftListModel;
  time051?: ShiftListModel;
  time052?: ShiftListModel;
  time053?: ShiftListModel;
  time061?: ShiftListModel;
  time062?: ShiftListModel;
  time063?: ShiftListModel;
  time071?: ShiftListModel;
  time072?: ShiftListModel;
  time073?: ShiftListModel;
  time081?: ShiftListModel;
  time082?: ShiftListModel;
  time083?: ShiftListModel;
  time091?: ShiftListModel;
  time092?: ShiftListModel;
  time093?: ShiftListModel;
  time101?: ShiftListModel;
  time102?: ShiftListModel;
  time103?: ShiftListModel;
  time111?: ShiftListModel;
  time112?: ShiftListModel;
  time113?: ShiftListModel;
  time121?: ShiftListModel;
  time122?: ShiftListModel;
  time123?: ShiftListModel;
  time131?: ShiftListModel;
  time132?: ShiftListModel;
  time133?: ShiftListModel;
  time141?: ShiftListModel;
  time142?: ShiftListModel;
  time143?: ShiftListModel;
  time151?: ShiftListModel;
  time152?: ShiftListModel;
  time153?: ShiftListModel;
  time161?: ShiftListModel;
  time162?: ShiftListModel;
  time163?: ShiftListModel;
  time171?: ShiftListModel;
  time172?: ShiftListModel;
  time173?: ShiftListModel;
  time181?: ShiftListModel;
  time182?: ShiftListModel;
  time183?: ShiftListModel;
  time191?: ShiftListModel;
  time192?: ShiftListModel;
  time193?: ShiftListModel;
  time201?: ShiftListModel;
  time202?: ShiftListModel;
  time203?: ShiftListModel;
  time211?: ShiftListModel;
  time212?: ShiftListModel;
  time213?: ShiftListModel;
  time221?: ShiftListModel;
  time222?: ShiftListModel;
  time223?: ShiftListModel;
  time231?: ShiftListModel;
  time232?: ShiftListModel;
  time233?: ShiftListModel;
  time241?: ShiftListModel;
  time242?: ShiftListModel;
  time243?: ShiftListModel;
  time251?: ShiftListModel;
  time252?: ShiftListModel;
  time253?: ShiftListModel;
  time261?: ShiftListModel;
  time262?: ShiftListModel;
  time263?: ShiftListModel;
  time271?: ShiftListModel;
  time272?: ShiftListModel;
  time273?: ShiftListModel;
  time281?: ShiftListModel;
  time282?: ShiftListModel;
  time283?: ShiftListModel;
  time291?: ShiftListModel;
  time292?: ShiftListModel;
  time293?: ShiftListModel;
  time301?: ShiftListModel;
  time302?: ShiftListModel;
  time303?: ShiftListModel;
  time311?: ShiftListModel;
  time312?: ShiftListModel;
  time313?: ShiftListModel;
}



export class MyShifTimetListModel extends BaseModel implements ShiftTimeListModel {
  yearId: number | undefined;
  monthId: number | undefined;
  time0Id: string | undefined;
  time011: ShiftListModel | undefined;
  time012: ShiftListModel | undefined;
  time013: ShiftListModel | undefined;
  time021: ShiftListModel | undefined;
  time022: ShiftListModel | undefined;
  time023: ShiftListModel | undefined;
  time031: ShiftListModel | undefined;
  time032: ShiftListModel | undefined;
  time033: ShiftListModel | undefined;
  time041: ShiftListModel | undefined;
  time042: ShiftListModel | undefined;
  time043: ShiftListModel | undefined;
  time051: ShiftListModel | undefined;
  time052: ShiftListModel | undefined;
  time053: ShiftListModel | undefined;
  time061: ShiftListModel | undefined;
  time062: ShiftListModel | undefined;
  time063: ShiftListModel | undefined;
  time071: ShiftListModel | undefined;
  time072: ShiftListModel | undefined;
  time073: ShiftListModel | undefined;
  time081: ShiftListModel | undefined;
  time082: ShiftListModel | undefined;
  time083: ShiftListModel | undefined;
  time091: ShiftListModel | undefined;
  time092: ShiftListModel | undefined;
  time093: ShiftListModel | undefined;
  time101: ShiftListModel | undefined;
  time102: ShiftListModel | undefined;
  time103: ShiftListModel | undefined;
  time111: ShiftListModel | undefined;
  time112: ShiftListModel | undefined;
  time113: ShiftListModel | undefined;
  time121: ShiftListModel | undefined;
  time122: ShiftListModel | undefined;
  time123: ShiftListModel | undefined;
  time131: ShiftListModel | undefined;
  time132: ShiftListModel | undefined;
  time133: ShiftListModel | undefined;
  time141: ShiftListModel | undefined;
  time142: ShiftListModel | undefined;
  time143: ShiftListModel | undefined;
  time151: ShiftListModel | undefined;
  time152: ShiftListModel | undefined;
  time153: ShiftListModel | undefined;
  time161: ShiftListModel | undefined;
  time162: ShiftListModel | undefined;
  time163: ShiftListModel | undefined;
  time171: ShiftListModel | undefined;
  time172: ShiftListModel | undefined;
  time173: ShiftListModel | undefined;
  time181: ShiftListModel | undefined;
  time182: ShiftListModel | undefined;
  time183: ShiftListModel | undefined;
  time191: ShiftListModel | undefined;
  time192: ShiftListModel | undefined;
  time193: ShiftListModel | undefined;
  time201: ShiftListModel | undefined;
  time202: ShiftListModel | undefined;
  time203: ShiftListModel | undefined;
  time211: ShiftListModel | undefined;
  time212: ShiftListModel | undefined;
  time213: ShiftListModel | undefined;
  time221: ShiftListModel | undefined;
  time222: ShiftListModel | undefined;
  time223: ShiftListModel | undefined;
  time231: ShiftListModel | undefined;
  time232: ShiftListModel | undefined;
  time233: ShiftListModel | undefined;
  time241: ShiftListModel | undefined;
  time242: ShiftListModel | undefined;
  time243: ShiftListModel | undefined;
  time251: ShiftListModel | undefined;
  time252: ShiftListModel | undefined;
  time253: ShiftListModel | undefined;
  time261: ShiftListModel | undefined;
  time262: ShiftListModel | undefined;
  time263: ShiftListModel | undefined;
  time271: ShiftListModel | undefined;
  time272: ShiftListModel | undefined;
  time273: ShiftListModel | undefined;
  time281: ShiftListModel | undefined;
  time282: ShiftListModel | undefined;
  time283: ShiftListModel | undefined;
  time291: ShiftListModel | undefined;
  time292: ShiftListModel | undefined;
  time293: ShiftListModel | undefined;
  time301: ShiftListModel | undefined;
  time302: ShiftListModel | undefined;
  time303: ShiftListModel | undefined;
  time311: ShiftListModel | undefined;
  time312: ShiftListModel | undefined;
  time313: ShiftListModel | undefined;

  constructor(data: Partial<ShiftTimeListModel>, translateService: TranslateService) {
      super(data, translateService);
      this.yearId = data.yearId
      this.monthId = data.monthId
      this.time0Id = data.time0Id
      this.time011 = data.time011? new MyShiftListModel(data.time011!,this.translateService) : data.time011;
      this.time012 = data.time012? new MyShiftListModel(data.time012!,this.translateService) : data.time012;
      this.time013 = data.time013? new MyShiftListModel(data.time013!,this.translateService) : data.time013;
      this.time021 = data.time021? new MyShiftListModel(data.time021!,this.translateService) : data.time021;
      this.time022 = data.time022? new MyShiftListModel(data.time022!,this.translateService) : data.time022;
      this.time023 = data.time023? new MyShiftListModel(data.time023!,this.translateService) : data.time023;
      this.time031 = data.time031? new MyShiftListModel(data.time031!,this.translateService) : data.time031;
      this.time032 = data.time032? new MyShiftListModel(data.time032!,this.translateService) : data.time032;
      this.time033 = data.time033? new MyShiftListModel(data.time033!,this.translateService) : data.time033;
      this.time041 = data.time041? new MyShiftListModel(data.time041!,this.translateService) : data.time041;
      this.time042 = data.time042? new MyShiftListModel(data.time042!,this.translateService) : data.time042;
      this.time043 = data.time043? new MyShiftListModel(data.time043!,this.translateService) : data.time043;
      this.time051 = data.time051? new MyShiftListModel(data.time051!,this.translateService) : data.time051;
      this.time052 = data.time052? new MyShiftListModel(data.time052!,this.translateService) : data.time052;
      this.time053 = data.time053? new MyShiftListModel(data.time053!,this.translateService) : data.time053;
      this.time061 = data.time061? new MyShiftListModel(data.time061!,this.translateService) : data.time061;
      this.time062 = data.time062? new MyShiftListModel(data.time062!,this.translateService) : data.time062;
      this.time063 = data.time063? new MyShiftListModel(data.time063!,this.translateService) : data.time063;
      this.time071 = data.time071? new MyShiftListModel(data.time071!,this.translateService) : data.time071;
      this.time072 = data.time072? new MyShiftListModel(data.time072!,this.translateService) : data.time072;
      this.time073 = data.time073? new MyShiftListModel(data.time073!,this.translateService) : data.time073;
      this.time081 = data.time081? new MyShiftListModel(data.time081!,this.translateService) : data.time081;
      this.time082 = data.time082? new MyShiftListModel(data.time082!,this.translateService) : data.time082;
      this.time083 = data.time083? new MyShiftListModel(data.time083!,this.translateService) : data.time083;
      this.time091 = data.time091? new MyShiftListModel(data.time091!,this.translateService) : data.time091;
      this.time092 = data.time092? new MyShiftListModel(data.time092!,this.translateService) : data.time092;
      this.time093 = data.time093? new MyShiftListModel(data.time093!,this.translateService) : data.time093;
      this.time101 = data.time101? new MyShiftListModel(data.time101!,this.translateService) : data.time101;
      this.time102 = data.time102? new MyShiftListModel(data.time102!,this.translateService) : data.time102;
      this.time103 = data.time103? new MyShiftListModel(data.time103!,this.translateService) : data.time103;
      this.time111 = data.time111? new MyShiftListModel(data.time111!,this.translateService) : data.time111;
      this.time112 = data.time112? new MyShiftListModel(data.time112!,this.translateService) : data.time112;
      this.time113 = data.time113? new MyShiftListModel(data.time113!,this.translateService) : data.time113;
      this.time121 = data.time121? new MyShiftListModel(data.time121!,this.translateService) : data.time121;
      this.time122 = data.time122? new MyShiftListModel(data.time122!,this.translateService) : data.time122;
      this.time123 = data.time123? new MyShiftListModel(data.time123!,this.translateService) : data.time123;
      this.time131 = data.time131? new MyShiftListModel(data.time131!,this.translateService) : data.time131;
      this.time132 = data.time132? new MyShiftListModel(data.time132!,this.translateService) : data.time132;
      this.time133 = data.time133? new MyShiftListModel(data.time133!,this.translateService) : data.time133;
      this.time141 = data.time141? new MyShiftListModel(data.time141!,this.translateService) : data.time141;
      this.time142 = data.time142? new MyShiftListModel(data.time142!,this.translateService) : data.time142;
      this.time143 = data.time143? new MyShiftListModel(data.time143!,this.translateService) : data.time143;
      this.time151 = data.time151? new MyShiftListModel(data.time151!,this.translateService) : data.time151;
      this.time152 = data.time152? new MyShiftListModel(data.time152!,this.translateService) : data.time152;
      this.time153 = data.time153? new MyShiftListModel(data.time153!,this.translateService) : data.time153;
      this.time161 = data.time161? new MyShiftListModel(data.time161!,this.translateService) : data.time161;
      this.time162 = data.time162? new MyShiftListModel(data.time162!,this.translateService) : data.time162;
      this.time163 = data.time163? new MyShiftListModel(data.time163!,this.translateService) : data.time163;
      this.time171 = data.time171? new MyShiftListModel(data.time171!,this.translateService) : data.time171;
      this.time172 = data.time172? new MyShiftListModel(data.time172!,this.translateService) : data.time172;
      this.time173 = data.time173? new MyShiftListModel(data.time173!,this.translateService) : data.time173;
      this.time181 = data.time181? new MyShiftListModel(data.time181!,this.translateService) : data.time181;
      this.time182 = data.time182? new MyShiftListModel(data.time182!,this.translateService) : data.time182;
      this.time183 = data.time183? new MyShiftListModel(data.time183!,this.translateService) : data.time183;
      this.time191 = data.time191? new MyShiftListModel(data.time191!,this.translateService) : data.time191;
      this.time192 = data.time192? new MyShiftListModel(data.time192!,this.translateService) : data.time192;
      this.time193 = data.time193? new MyShiftListModel(data.time193!,this.translateService) : data.time193;
      this.time201 = data.time201? new MyShiftListModel(data.time201!,this.translateService) : data.time201;
      this.time202 = data.time202? new MyShiftListModel(data.time202!,this.translateService) : data.time202;
      this.time203 = data.time203? new MyShiftListModel(data.time203!,this.translateService) : data.time203;
      this.time211 = data.time211? new MyShiftListModel(data.time211!,this.translateService) : data.time211;
      this.time212 = data.time212? new MyShiftListModel(data.time212!,this.translateService) : data.time212;
      this.time213 = data.time213? new MyShiftListModel(data.time213!,this.translateService) : data.time213;
      this.time221 = data.time221? new MyShiftListModel(data.time221!,this.translateService) : data.time221;
      this.time222 = data.time222? new MyShiftListModel(data.time222!,this.translateService) : data.time222;
      this.time223 = data.time223? new MyShiftListModel(data.time223!,this.translateService) : data.time223;
      this.time231 = data.time231? new MyShiftListModel(data.time231!,this.translateService) : data.time231;
      this.time232 = data.time232? new MyShiftListModel(data.time232!,this.translateService) : data.time232;
      this.time233 = data.time233? new MyShiftListModel(data.time233!,this.translateService) : data.time233;
      this.time241 = data.time241? new MyShiftListModel(data.time241!,this.translateService) : data.time241;
      this.time242 = data.time242? new MyShiftListModel(data.time242!,this.translateService) : data.time242;
      this.time243 = data.time243? new MyShiftListModel(data.time243!,this.translateService) : data.time243;
      this.time251 = data.time251? new MyShiftListModel(data.time251!,this.translateService) : data.time251;
      this.time252 = data.time252? new MyShiftListModel(data.time252!,this.translateService) : data.time252;
      this.time253 = data.time253? new MyShiftListModel(data.time253!,this.translateService) : data.time253;
      this.time261 = data.time261? new MyShiftListModel(data.time261!,this.translateService) : data.time261;
      this.time262 = data.time262? new MyShiftListModel(data.time262!,this.translateService) : data.time262;
      this.time263 = data.time263? new MyShiftListModel(data.time263!,this.translateService) : data.time263;
      this.time271 = data.time271? new MyShiftListModel(data.time271!,this.translateService) : data.time271;
      this.time272 = data.time272? new MyShiftListModel(data.time272!,this.translateService) : data.time272;
      this.time273 = data.time273? new MyShiftListModel(data.time273!,this.translateService) : data.time273;
      this.time281 = data.time281? new MyShiftListModel(data.time281!,this.translateService) : data.time281;
      this.time282 = data.time282? new MyShiftListModel(data.time282!,this.translateService) : data.time282;
      this.time283 = data.time283? new MyShiftListModel(data.time283!,this.translateService) : data.time283;
      this.time291 = data.time291? new MyShiftListModel(data.time291!,this.translateService) : data.time291;
      this.time292 = data.time292? new MyShiftListModel(data.time292!,this.translateService) : data.time292;
      this.time293 = data.time293? new MyShiftListModel(data.time293!,this.translateService) : data.time293;
      this.time301 = data.time301? new MyShiftListModel(data.time301!,this.translateService) : data.time301;
      this.time302 = data.time302? new MyShiftListModel(data.time302!,this.translateService) : data.time302;
      this.time303 = data.time303? new MyShiftListModel(data.time303!,this.translateService) : data.time303;
      this.time311 = data.time311? new MyShiftListModel(data.time311!,this.translateService) : data.time311;
      this.time312 = data.time312? new MyShiftListModel(data.time312!,this.translateService) : data.time312;
      this.time313 = data.time313? new MyShiftListModel(data.time313!,this.translateService) : data.time313;
  }

}

